baseurl = "https://whitelisted2.github.io/"
title = "Siddharth Prabhu"
theme = "hugo-coder"

publishDir = "build"
languagecode = "en"
defaultcontentlanguage = "en"
relativeurls = true


[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'gruvbox'

[params]
  author = "Siddharth Prabhu"
  info = "Recent MS Graduate (Hire me!)"
  description = "Siddharth Prabhu's Personal Website"
  keywords = "blog,developer,personal"
  avatarurl = "/images/sidpfp.png"
  #gravatar = "bsiddharthprabhu9@gmail.com"

  faviconSVG = "/images/babasprite64.gif"
  favicon_32 = "/images/babasprite64.gif"
  favicon_16 = "/images/babasprite64.gif"

  since = 2026

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  icon = 'fa fa-envelope fa-2x'
  name = 'Email'
  weight = 10
  url = 'mailto:bsiddharthprabhu9@gmail.com'
[[params.social]]
  icon = 'fa fa-linkedin fa-2x'
  name = 'LinkedIn'
  weight = 15
  url = 'https://linkedin.com/in/b-siddharth-prabhu'
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 20
  url = "https://github.com/whitelisted2/"


# Menu links
[[menu.main]]
  name = "Résumé"
  weight = 10
  url  = "/resume/"
[[menu.main]]
  name = "Blog"
  weight = 30
  url  = "/posts/"
[[menu.main]]
  name = "Gallery"
  weight = 40
  url  = "/gallery/"
[[menu.main]]
  name = "About"
  weight = 100
  url = "/about/"
